# Generated by Django 3.1.2 on 2020-10-16 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('health', models.IntegerField()),
                ('atkmin', models.IntegerField()),
                ('atkmax', models.IntegerField()),
                ('sprite', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('attack', models.IntegerField()),
                ('sprite', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('health', models.IntegerField()),
                ('atkmin', models.IntegerField()),
                ('atkmax', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sprite', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('equip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.market')),
            ],
        ),
    ]
