# Generated by Django 3.1.2 on 2020-10-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='atkmax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='atkmin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='sprite',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sprite',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='atkmax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market',
            name='atkmin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market',
            name='sprite',
            field=models.TextField(blank=True),
        ),
    ]
