# Generated by Django 3.1 on 2020-10-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201016_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
