# Generated by Django 3.1 on 2020-10-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
    ]
