# Generated by Django 3.1 on 2020-10-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_member_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
    ]
