# Generated by Django 3.1 on 2020-10-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201017_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='price',
            new_name='cash',
        ),
    ]
