# Generated by Django 3.1 on 2020-10-18 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201017_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
