# Generated by Django 3.1 on 2020-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_player_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cash',
            field=models.IntegerField(default=300),
        ),
    ]
