# Generated by Django 3.1 on 2020-10-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201018_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='equip',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.equipment'),
        ),
    ]
