# Generated by Django 3.1 on 2020-10-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201018_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.market'),
        ),
    ]
